### ISSUE TITLE
Rescale and index measure

### ISSUE THREAD

**Issue by alanyan19** [jaeyk/validating-two-linked-fates#15]
Could you rescale the measures from 0 to 1 for more interpretability? Also, could you index our two measures and rescale form 0 to 1 so we can make the point that Whites score lower on our scores clearly? Thanks!

**Comment by jaeyk** [comment]
@alanyan19 Fixed it. Note that I rescaled the responses so that they could range from -1 to 1 (I think that's easier to interpret as if we do the scale from 0 to 1 the readers need to understand that a value < 0.5 indicates a negative response).
